name: Run GUI Test Review

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  call-gui-test:
    uses: DigitalProductInnovationAndDevelopment/Code-Reviews-of-GUI-Tests/.github/workflows/playwright.yml@main
    