# File: .github/workflows/use-reusable-workflow.yml
name: Run GUI Test Review via Reusable Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  reuse-gui-test:
    uses: your-org/your-repo/.github/workflows/playwright.yml@main